## Global site settings.

# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, you should restart the server
# process. If you find yourself editing this file very often, consider using
# Jekyll's data files feature instead.
#
# These variables can be accessed by templates, e.g. ``{{ site.myvariable }}``.

## General metadata
title: Chris Barrick
email: cbarrick1@gmail.com
tagline: Chris Barrick's personal website and blog
description: >-
  Chris Barrick's personal website and blog
timezone: America/New_York
encoding: utf-8
permalink: /:title
lang: en-US
license:
  spdx: CC-BY-SA-4.0
  url: https://creativecommons.org/licenses/by/4.0/

## Author / SEO metadata
# <https://jekyll.github.io/jekyll-seo-tag/>
author:
  name: Chris Barrick
  url: https://cbarrick.dev
  github: cbarrick
  mastodon: "@csb@hachyderm.io"
  twitter: cbarrick1024
  linkedin: csb1024
github:
  username: cbarrick
  url: https://github.com/cbarrick
mastodon:
  username: "@csb@hachyderm.io"
  url: https://hachyderm.io/@csb
twitter:
  username: cbarrick1024
  url: https://twitter.com/cbarrick1024
  card: summary
linkedin:
  username: csb1024
  url: https://www.linkedin.com/in/csb1024/
social:
  name: Chris Barrick
  links:
    - https://github.com/cbarrick
    - https://twitter.com/cbarrick1024
    - https://hachyderm.io/@csb
    - https://www.linkedin.com/in/csb1024/
    - https://www.facebook.com/chris.barrick1024
webmaster_verifications:
  google: W4TaAXnMBUryBO_-3cRLRqCHaXuk72rXMbzCOfnOvUI # https://search.google.com/search-console
  facebook: jp014ow2qwzugibwm6wgpmer3kj1e3 # https://business.facebook.com/settings

## Cannonical URL
url: "https://cbarrick.dev"
baseurl: ""

## Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: false
sass:
  style: compressed

## Plugins
# Github Pages only supports plugins on their whitelist.
# <https://pages.github.com/versions/>
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

## Collections
# Technically, the "posts" collection is setup by default.
# We reset it here for the sake of being explicit.
collections:
  posts:
    output: true

## Front matter defaults
# Set default frontmatter metadata using these rules.
# <https://jekyllrb.com/docs/configuration/front-matter-defaults/>
defaults:
  - scope:
      path: ""
      type: posts
    values:
      permalink: /posts/:year/:month/:day/:title
      layout: post
